export const UF_list = [
    {key: 12, name: "AC - Acre"},
    {key: 27, name: "AL - Alagoas"},
    {key: 16, name: "AP - Amapá"},
    {key: 13, name: "AM - Amazonas"},
    {key: 29, name: "BA - Bahia"},
    {key: 23, name: "CE - Ceará"},
    {key: 53, name: "DF - Distrito Federal"},
    {key: 32, name: "ES - Espírito Santo"},
    {key: 52, name: "GO - Goiás"},
    {key: 21, name: "MA - Maranhão"},
    {key: 51, name: "MT - Mato Grosso"},
    {key: 50, name: "MS - Mato Grosso do Sul"},
    {key: 31, name: "MG - Minas Gerais"},
    {key: 15, name: "PA - Pará"},
    {key: 25, name: "PB - Paraíba"},
    {key: 41, name: "PR - Paraná"},
    {key: 26, name: "PE - Pernambuco"},
    {key: 22, name: "PI - Piauí"},
    {key: 33, name: "RJ - Rio de Janeiro"},
    {key: 24, name: "RN - Rio Grande do Norte"},
    {key: 43, name: "RS - Rio Grande do Sul"},
    {key: 11, name: "RO - Rondônia"},
    {key: 14, name: "RR - Roraima"},
    {key: 42, name: "SC - Santa Catarina"},
    {key: 35, name: "SP - São Paulo"},
    {key: 28, name: "SE - Sergipe"},
    {key: 17, name: "TO - Tocantins"},
];